# libs
Аналоги:  
- https://mlbox.readthedocs.io/en/latest/  
- https://lightautoml.readthedocs.io/  
- https://automl.github.io/auto-sklearn/master/  

Tюнинг:
- https://optuna.org/
- https://hyperopt.github.io/hyperopt/
- https://docs.ray.io/en/latest/tune/index.html 
- https://oss-vizier.readthedocs.io/en/latest/ 

Работа с фичами:
- https://scikit-learn.org/1.5/modules/feature_selection.html
- https://feature-engine.trainindata.com/en/1.7.x/api_doc/selection/index.html
- https://github.com/AutoViML/featurewiz
- https://github.com/scikit-learn-contrib/boruta_py

Прочее:
- https://unit8co.github.io/darts/
- https://epistasislab.github.io/tpot/  

# datasets
Сберовский датасет:
- https://huggingface.co/datasets/ai-lab/MBD (14,6 GB, основной датасет)
- https://huggingface.co/datasets/ai-lab/MBD-mini (3,38 GB, уменьшенная версия, 10% клиентов из основного датасета)  

Kaggle datasets:
- https://www.kaggle.com/datasets/yasserh/titanic-dataset
- https://www.kaggle.com/datasets/rabieelkharoua/predict-liver-disease-1700-records-dataset
- https://www.kaggle.com/datasets/devzohaib/eligibility-prediction-for-loan
- https://www.kaggle.com/datasets/deepcontractor/smoke-detection-dataset
- https://www.kaggle.com/datasets/stealthtechnologies/employee-attrition-dataset
- https://www.kaggle.com/datasets/rabieelkharoua/cancer-prediction-dataset
- https://www.kaggle.com/datasets/yasserh/heart-disease-dataset
- https://www.kaggle.com/datasets/rabieelkharoua/predict-online-course-engagement-dataset
- https://www.kaggle.com/datasets/rabieelkharoua/predicting-hiring-decisions-in-recruitment-data
- https://www.kaggle.com/datasets/barun2104/telecom-churn
- https://www.kaggle.com/datasets/rabieelkharoua/predicting-manufacturing-defects-dataset
- https://www.kaggle.com/datasets/rabieelkharoua/predict-customer-purchase-behavior-dataset
- https://www.kaggle.com/datasets/teejmahal20/airline-passenger-satisfaction
- https://www.kaggle.com/datasets/dhanushnarayananr/credit-card-fraud
- https://www.kaggle.com/datasets/rameshmehta/credit-risk-analysis
- https://www.kaggle.com/datasets/marcpaulo/titanic-huge-dataset-1m-passengers
- https://www.kaggle.com/datasets/manishtripathi86/fedex-data
- https://www.kaggle.com/datasets/ban7002/fraud-challenge-data
- https://www.kaggle.com/datasets/ulrikthygepedersen/kickstarter-projects


In [1]:
import numpy as np
import pandas as pd
import polars as pl

import kaggle
import time
from pathlib import Path

kaggle.api.authenticate()

In [2]:
datasets = [
    {
        'link': 'https://www.kaggle.com/datasets/yasserh/titanic-dataset', 
        'target': 'Survived',
        'id_cols': ['PassengerId',],
    },
    {
        'link': 'https://www.kaggle.com/datasets/rabieelkharoua/predict-liver-disease-1700-records-dataset', 
        'target': 'Diagnosis',
    },
    {
        'link': 'https://www.kaggle.com/datasets/devzohaib/eligibility-prediction-for-loan', 
        'target': 'Loan_Status',
        'id_cols': ['Loan_ID',],
    },
    {
        'link': 'https://www.kaggle.com/datasets/deepcontractor/smoke-detection-dataset', 
        'target': 'Fire Alarm',
        'id_cols': ['index',],
    },
    {
        'link': 'https://www.kaggle.com/datasets/stealthtechnologies/employee-attrition-dataset', 
        'target': 'Attrition',
        'id_cols': ['Employee ID',],
    },
    {
        'link': 'https://www.kaggle.com/datasets/rabieelkharoua/cancer-prediction-dataset', 
        'target': 'Diagnosis',
    },
    {
        'link': 'https://www.kaggle.com/datasets/yasserh/heart-disease-dataset', 
        'target': 'target',
    },
    {
        'link': 'https://www.kaggle.com/datasets/rabieelkharoua/predict-online-course-engagement-dataset', 
        'target': 'CourseCompletion',
        'id_cols': ['UserID',],
    },
    {
        'link': 'https://www.kaggle.com/datasets/rabieelkharoua/predicting-hiring-decisions-in-recruitment-data', 
        'target': 'HiringDecision',
    },
    {
        'link': 'https://www.kaggle.com/datasets/barun2104/telecom-churn', 
        'target': 'Churn',
    },
    {
        'link': 'https://www.kaggle.com/datasets/rabieelkharoua/predicting-manufacturing-defects-dataset', 
        'target': 'DefectStatus',
    },
    {
        'link': 'https://www.kaggle.com/datasets/rabieelkharoua/predict-customer-purchase-behavior-dataset',
        'target': 'PurchaseStatus',
    },
    {
        'link': 'https://www.kaggle.com/datasets/teejmahal20/airline-passenger-satisfaction', 
        'target': 'Satisfaction',
    },
    {
        'link': 'https://www.kaggle.com/datasets/dhanushnarayananr/credit-card-fraud', 
        'target': 'fraud',
    },
    {
        'link': 'https://www.kaggle.com/datasets/rameshmehta/credit-risk-analysis', 
        'target': 'default_ind',
        'id_cols': ['id', 'member_id',],
        'time_col': 'issue_d',
    },
    {
        'link': 'https://www.kaggle.com/datasets/marcpaulo/titanic-huge-dataset-1m-passengers', 
        'target': 'Survived',
        'id_cols': ['PassengerId',],
    },
    # {
    #     'link': 'https://www.kaggle.com/datasets/manishtripathi86/fedex-data', 
    #     'target': 'Delivery_Status',
    #     'time_col': 'Year',
    # },
    {
        'link': 'https://www.kaggle.com/datasets/ban7002/fraud-challenge-data', 
        'target': 'EVENT_LABEL',
        'time_col': 'EVENT_TIMESTAMP',
    },
    # {
    #     'link': 'https://www.kaggle.com/datasets/ulrikthygepedersen/kickstarter-projects', 
    #     'target': 'State',
    #     'id_cols': ['ID',],
    #     'time_col': 'Launched',
    # },
]

In [3]:
for dataset in datasets:
    dataset_name = dataset['link'].replace('https://www.kaggle.com/datasets/', '')
    dataset_path = Path(f'./datasets/{dataset_name}')
    if not dataset_path.exists():
        if len(dataset_path.glob('*.csv')) == 0:
            kaggle.api.dataset_download_files(dataset_name, path=dataset_path, unzip=True)

In [4]:
def get_train_test_datasets(datasets, datasets_path, test_size=0.3, random_state=0):
    from tqdm import tqdm
    from pathlib import Path
    from sklearn.model_selection import train_test_split
    from sklearn.preprocessing import LabelEncoder
    
    
    for dataset in tqdm(datasets):
        dataset_name = dataset['link'].replace('https://www.kaggle.com/datasets/', '')
        files = list((Path(datasets_path) / dataset_name).glob('*.csv'))
        if len(files) == 1:
            dataset_path = files[0]
            data = pd.read_csv(dataset_path)
            target_name = dataset['target']
            data = data.dropna(subset=[target_name])
            
            if dataset.get('id_cols'):
                data = data.drop(columns=[dataset['id_cols']], errors='ignore')

            le = LabelEncoder()
            data[target_name] = le.fit_transform(data[target_name])
            data = data.select_dtypes(include=[np.number]).dropna(how='all', axis='columns').fillna(0)
            train_data, test_data = train_test_split(
                data, 
                test_size=test_size, 
                stratify=data[target_name], 
                random_state=random_state
            )
            yield train_data, test_data, target_name, dataset_name

# Модуль model

In [5]:
%load_ext autoreload
%autoreload 2

## sklearn metrics

In [8]:
from automl import AutoML
from sklearn.metrics import roc_auc_score


results = []
for train, test, target_name, dataset_name in get_train_test_datasets(datasets, datasets_path='./datasets', test_size=0.3, random_state=0):
    train, test = train, test
    start_time = time.perf_counter()
    automl = AutoML(
        task='classification',
        use_preprocessing_pipeline=False,
        feature_selector_type=None,
        use_val_test_pipeline=False,
        auto_models_init_kwargs = {
            "metric": "roc_auc",
            "time_series": False,
            "models_list": ["all"],
            "blend": True,
            "stack": True
        },
        n_jobs=12, 
        random_state=0,
        )
    automl = automl.fit(
        train.drop(columns=[target_name,]), train[target_name].to_numpy(), 
        test.drop(columns=[target_name,]), test[target_name].to_numpy(),
        auto_model_fit_kwargs = {
            "tuning_timeout": 10
        }
    )
    train_time = time.perf_counter() - start_time
    
    test_predictions = automl.predict(test.drop(columns=[target_name,]))
    predict_time = time.perf_counter() - start_time - train_time
    all_time = train_time + predict_time
    
    test_score = roc_auc_score(test[target_name], test_predictions[:, 1])
    results.append((dataset_name, test_score))

[2025-02-14 13:19:03,772] - [   MODEL    ] - 1 out of 10. type
[2025-02-14 13:19:03,774] - [   START    ] - Working with type
[2025-02-14 13:19:03,775] - [   START    ] - Tuning type
[2025-02-14 13:19:04,893] - [   OPTUNA   ] - Trial 0. New best score 0.7167475779632835 with parameters {'max_iter': 8277, 'fit_intercept': True, 'C': 1.8590843630169627, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.9636627605010293}
[2025-02-14 13:19:05,955] - [   OPTUNA   ] - Trial 1. New best score 0.7170224127775919 with parameters {'max_iter': 5813, 'fit_intercept': True, 'C': 2.5601615250028704, 'solver': 'saga', 'penalty': 'none'}
[2025-02-14 13:19:06,970] - [   OPTUNA   ] - Trial 2. New best score 0.7197683219169781 with parameters {'max_iter': 12506, 'fit_intercept': False, 'C': 744.2349368719797, 'solver': 'saga', 'penalty': 'none'}
[2025-02-14 13:19:09,056] - [   OPTUNA   ] - Trial 4. New best score 0.7198240251256768 with parameters {'max_iter': 8570, 'fit_intercept': False, 'C': 4.

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [28]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, ConfusionMatrixDisplay
from collections import Counter

# Создаём несбалансированный набор данных
X, y = make_classification(n_classes=2, class_sep=2, 
                           weights=[0.9, 0.1], # 90% одного класса, 10% другого
                           n_samples=100, n_features=10, random_state=42)

# Проверяем баланс классов
print(f"Распределение классов: {Counter(y)}")

# Функция для тестирования class_weight
def test_class_weight(class_weight):
    model = RandomForestClassifier(class_weight=class_weight, random_state=42, n_estimators=100, bootstrap=False)
    model.fit(X, y)
    y_pred = model.predict(X)
    
    print(f"\n=== class_weight={class_weight} ===")

# 1. Без балансировки
test_class_weight(None)

# 2. Автоматическая балансировка
test_class_weight("balanced")

# 2. Автоматическая балансировка
test_class_weight("balanced_subsample")

# 3. Явное задание весов (например, уменьшаем перевес в 5 раз)
test_class_weight({0: 1, 1: 5})

Распределение классов: Counter({0: 90, 1: 10})

=== class_weight=None ===

=== class_weight=balanced ===

=== class_weight=balanced_subsample ===

=== class_weight={0: 1, 1: 5} ===


In [31]:
y[0] = 0.001

In [32]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0])

In [18]:
from sklearn.utils.class_weight import compute_class_weight

y = np.array([0, 0, 0])
compute_class_weight('balanced', classes=np.unique(y), y=y)

array([1.])

In [7]:
results

[('yasserh/titanic-dataset', 0.7718152397764049),
 ('rabieelkharoua/predict-liver-disease-1700-records-dataset',
  0.9383984211098853),
 ('devzohaib/eligibility-prediction-for-loan', 0.7440266087428727)]

In [39]:
from automl.model.catboost import CatBoostClassification, CatBoostRegression
from automl.model.lightgbm import LightGBMClassification, LightGBMRegression
from automl.model.xgboost import XGBClassification, XGBRegression
from automl.model.sklearn import ExtraTreesClassification, ExtraTreesRegression
from automl.model.sklearn import RandomForestClassification, RandomForestRegression
from automl.model.sklearn import LogisticRegression, RidgeRegression
from automl.model.lama import TabularLamaClassification, TabularLamaRegression
from automl.model.lama import TabularLamaUtilizedClassification, TabularLamaUtilizedRegression


model = RandomForestClassification(n_splits=2, n_jobs=1, num_iterations=2, random_state=1)
model.tune(train.drop(columns=[target_name,]), train[target_name].to_numpy(), )

[2025-02-14 12:13:02,768] - [   START    ] - Tuning ABCMeta
[2025-02-14 12:13:02,768] - [   START    ] - Tuning ABCMeta
[2025-02-14 12:13:02,768] - [   START    ] - Tuning ABCMeta
[2025-02-14 12:13:02,768] - [   START    ] - Tuning ABCMeta
[2025-02-14 12:13:02,768] - [   START    ] - Tuning ABCMeta
[2025-02-14 12:13:02,768] - [   START    ] - Tuning ABCMeta
[2025-02-14 12:13:03,598] - [   OPTUNA   ] - Trial 0. New best score 0.7309119871907097 with parameters {'n_estimators': 423, 'max_depth': 12, 'min_samples_split': 2.2874963468977327e-05, 'min_samples_leaf': 0.060466514526367955, 'max_features': 0.23208030173540176, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}
[2025-02-14 12:13:18,515] - [   OPTUNA   ] - Trial 12. New best score 0.73238412552521 with parameters {'n_estimators': 857, 'max_depth': 5, 'min_samples_split': 0.040037769829065185, 'min_samples_leaf': 0.04872820966539076, 'max_features': 0.36908535128002506, 'bootstrap': True, 'max_samples': 0.946

In [16]:
import numpy as np
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# Создаем синтетические данные для примера
np.random.seed(42)
y = [0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,]
X = np.random.rand(len(y), 5) 
# Разделяем данные на обучающую и тестовую выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Создаем модель ExtraTreesRegressor
model = ExtraTreesRegressor(**{
    'n_estimators': 162, 
    'max_depth': 10, 
    'min_samples_split': 0.05738637015674741, 
    'min_samples_leaf': 0.0808205755459821, 
    'max_features': 0.7034906283443978, 
    'bootstrap': True, 
    'max_samples': 0.014692718456558174, 
    # 'oob_score': False,
    })

# Обучаем модель на обучающей выборке
model.fit(X_train, y_train)

# Делаем предсказания на тестовой выборке
y_pred = model.predict(X_test)

# Оцениваем качество модели с помощью среднеквадратичной ошибки (MSE)
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse:.4f}")

# Пример предсказания для новых данных
new_data = np.array([[0.5, 0.3, 0.2, 0.1, 0.4]])
prediction = model.predict(new_data)
print(f"Prediction for new data: {prediction[0]:.4f}")

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [5]:
X_test

array([[0.12203823, 0.49517691, 0.03438852, 0.9093204 , 0.25877998],
       [0.86310343, 0.62329813, 0.33089802, 0.06355835, 0.31098232],
       [0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.87146059, 0.80367208, 0.18657006, 0.892559  , 0.53934224],
       [0.92187424, 0.0884925 , 0.19598286, 0.04522729, 0.32533033]])

In [9]:
model.predict(X_test)

array([nan, nan, nan, nan, nan])